language: android

android:
  components:
    - build-tools-19.1.0
    - android-19
    - sys-img-armeabi-v7a-android-19

before_script:
  - npm install -g bower
  - bower install

script:
  - make assets build
